package entities;
// Generated 22 ene 2026, 13:21:33 by Hibernate Tools 6.5.1.Final

/**
 * Entidades generated by hbm2java
 */
public class Entidades implements java.io.Serializable {

	private String nombre;

	public Entidades() {
	}

	public Entidades(String nombre) {
		this.nombre = nombre;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getIdEntidad() {
		return this.getIdEntidad();
	}

}
