package entities;
// Generated 22 ene 2026, 13:21:33 by Hibernate Tools 6.5.1.Final

/**
 * Registro generated by hbm2java
 */
public class Registro implements java.io.Serializable {

	private int idRegistro;
	private String dniSolicitante;
	private String nombreSolicitante;
	private String apellidosSolicitante;
	private String tramite;
	private String entidad;

	public Registro() {
	}

	public Registro(int idRegistro, String dniSolicitante, String nombreSolicitante, String apellidosSolicitante,
			String tramite, String entidad) {
		this.idRegistro = idRegistro;
		this.dniSolicitante = dniSolicitante;
		this.nombreSolicitante = nombreSolicitante;
		this.apellidosSolicitante = apellidosSolicitante;
		this.tramite = tramite;
		this.entidad = entidad;
	}

	public int getIdRegistro() {
		return this.idRegistro;
	}

	public void setIdRegistro(int idRegistro) {
		this.idRegistro = idRegistro;
	}

	public String getDniSolicitante() {
		return this.dniSolicitante;
	}

	public void setDniSolicitante(String dniSolicitante) {
		this.dniSolicitante = dniSolicitante;
	}

	public String getNombreSolicitante() {
		return this.nombreSolicitante;
	}

	public void setNombreSolicitante(String nombreSolicitante) {
		this.nombreSolicitante = nombreSolicitante;
	}

	public String getApellidosSolicitante() {
		return this.apellidosSolicitante;
	}

	public void setApellidosSolicitante(String apellidosSolicitante) {
		this.apellidosSolicitante = apellidosSolicitante;
	}

	public String getTramite() {
		return this.tramite;
	}

	public void setTramite(String tramite) {
		this.tramite = tramite;
	}

	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad2) {
		this.entidad = entidad2;
	}

}
